name: Check-Changelog

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') == 0 }}
    steps:
      - name: Get PR number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Check the changelog only if tests have been modified
        run: |
          set -x
          tests=`git diff --name-only origin/master | grep tests`
          if [ "$tests" != "" ]
          then
            result=`grep "$PR_NUMBER" ./changelog.rst`
            if [ "$result" != "" ]
            then
              echo $result
            else
            then
              echo "Changelog entry is missing."
              exit 1
            fi
          fi
